image: golang:1.12.0-alpine3.9

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - inspect
  - build

before_script:
  - apk add git make

inspect:
  coverage: '/coverage: \d+.\d+% of statements/'
  stage: inspect
  script:
    - make go-coverage

build:
  stage: build
  script:
    - make go-build
