name: Continuous integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.20'

      - run: make go-coverage

      - uses: actions/upload-artifact@v3.1.3
        with:
          name: coverage.html
          path: /tmp/coverage.html

  docker-build:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build the Docker image
        run: make docker-build
