name: Continuous integration

on: [push]

jobs:

  checks:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.16'
      - run: make go-coverage
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: coverage.html
          path: /tmp/coverage.html

  docker-build:
    if: github.ref == 'refs/heads/master'
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: Build the Docker image
        run: make docker-build
