name: Continuous integration

on: [push]

jobs:

  checks:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.13'
      - run: make go-coverage
      - uses: actions/upload-artifact@v1
        with:
          name: coverage.html
          path: /tmp/coverage.html

  docker-build:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build the Docker image
        run: make docker-build
