name: Continuous integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-go@v5.2.0
        with:
          go-version-file: go.mod

      - run: make go-coverage

      - uses: actions/upload-artifact@v4.6.0
        with:
          name: coverage.html
          path: /tmp/coverage.html

  docker-build:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build the Docker image
        run: make docker-build

