name: Continuous integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          submodules: true

      - uses: actions/setup-go@v6.0.0
        with:
          go-version-file: go.mod

      - name: Coverage test
        run: |
          set -o pipefail
          make go-coverage 2>&1 | tee coverage.log

      - name: Generate summary
        run: |
          echo "# Coverage" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat coverage.log | grep "$(basename $PWD).*coverage:" | cut -d$'\t' -f2,4 | sed "s/\tcoverage//" | sed "s/ of statements//" >> $GITHUB_STEP_SUMMARY
          cat coverage.log | grep "^total:" | sed "s/(statements)//" | tr -s "\t" | sed 's/\t/ /g' >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v5.0.0
        with:
          name: coverage.html
          path: .build/coverage/coverage.html

  docker-build:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          submodules: true

      - name: Build the Docker image
        run: make docker-build

